before_install:
    - rvm use 1.9.3
    - gem install bundler
    - apt-get install nodejs
install:
    - npm install
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
